resource "aws_db_subnet_group" "this" {
  name       = "${var.name_prefix}-db"
  subnet_ids = var.private_subnet_ids
  tags       = merge(var.tags, { Name = "${var.name_prefix}-db-subnet-group" })
}

# The master password is generated by Terraform and stored only in Secrets Manager
# (below) — never in a .tfvars file, never in state in plaintext beyond what Terraform's
# own state encryption already covers. See infra/terraform/README.md for state-file
# handling once a real backend is configured.
resource "random_password" "master" {
  length  = 32
  special = false # RDS master passwords disallow "/", "@", "\"", and space — simplest to exclude all specials
}

resource "aws_db_instance" "this" {
  identifier     = "${var.name_prefix}-db"
  engine         = "postgres"
  engine_version = "16.4"

  # db.t4g.micro is the right *starting* size for a pre-alpha closed cohort, not a
  # permanent choice — see ARCHITECTURE.md §2 on not over-provisioning for load that
  # doesn't exist yet. Resize (or move to Multi-AZ) once real usage data justifies it.
  instance_class        = var.instance_class
  allocated_storage     = var.allocated_storage_gb
  max_allocated_storage = var.max_allocated_storage_gb # enables storage autoscaling
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = var.database_name
  username = var.master_username
  password = random_password.master.result
  port     = 5432

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [var.database_security_group_id]
  publicly_accessible    = false

  multi_az = var.multi_az

  backup_retention_period = var.backup_retention_days
  backup_window           = "03:00-04:00" # UTC — low-traffic window assumption, revisit once there's real usage data
  maintenance_window      = "mon:04:30-mon:05:30"

  deletion_protection = var.deletion_protection
  skip_final_snapshot = !var.deletion_protection
  # A fixed identifier, not a timestamp()-derived one — timestamp() re-evaluates on every
  # plan/apply, which would make this field (and therefore every plan) perpetually show a
  # diff even when nothing real changed. If a real destroy ever happens and a second final
  # snapshot under the same name is attempted later, AWS will error on the name collision
  # and the identifier can be bumped by hand at that point — a rare edge case, not a
  # reason to accept a perpetual diff on every single plan in the meantime.
  final_snapshot_identifier = var.deletion_protection ? "${var.name_prefix}-db-final-snapshot" : null

  enabled_cloudwatch_logs_exports = ["postgresql", "upgrade"]

  tags = merge(var.tags, { Name = "${var.name_prefix}-db" })

  lifecycle {
    # The engine_version/instance_class fields above are the deployment's evergreen
    # settings; AWS applies minor-version patches automatically (auto_minor_version_upgrade
    # defaults true) and Terraform shouldn't fight that by trying to revert engine_version
    # drift on every plan.
    ignore_changes = [engine_version]
  }
}
